# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: |
          echo "color=blue" >> "$GITHUB_OUTPUT"
      - name: Get color
        env: 
          color: ${{ steps.color-selector.outputs.color }}
        run: echo "The selected color is $color"
        
  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
            echo "sentence='this is a sentence'" >> "$GITHUB_OUTPUT"
    outputs:
      SENTENCE: ${{ steps.sentence_maker.outputs.sentence }}

  consumer:
    needs: producer
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: |
          echo ${{ needs.producer.outputs.SENTENCE }}

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        id: calculate
        run: |
          expr 3 + 7 > result.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculation-result 
          path: result.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: calculation-result
          path: ./result.txt 

      - shell: bash
        run: |
          value=`cat result.txt`
          echo $(expr $value \* 9) 